"""One generated page per major component (pillar) for agent-utilities (D4).

AU's own ``architecture/component-registry.yml`` has exactly 1 component --
too sparse to seed a components tier the way epistemic-graph's 6-component
registry does (see ``render_components.py``). AU's ``docs/concepts.yaml``
pillars are the honest analogue: 9 top-level groupings over 1229 concepts,
already generated (by AU's own ``scripts/build_concepts_yaml.py``) and
already used as this corpus's Concept tier for AU (``skill_graph/au.py``).
This module renders one page per pillar, listing every concept under it.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

import yaml

from skill_graph.model import slugify


def _load_concepts(repo_root: Path) -> dict[str, Any] | None:
    concepts_path = repo_root / "docs" / "concepts.yaml"
    if not concepts_path.is_file():
        return None
    return yaml.safe_load(concepts_path.read_text(encoding="utf-8")) or {}


def _group_by_pillar(concepts: list[dict[str, Any]]) -> dict[str, list[dict[str, Any]]]:
    by_pillar: dict[str, list[dict[str, Any]]] = {}
    for concept in concepts:
        by_pillar.setdefault(concept.get("pillar") or "unspecified", []).append(concept)
    return by_pillar


def _render_concept_line(concept: dict[str, Any]) -> str:
    concept_id = concept.get("id", "")
    name = concept.get("name") or ""
    label = f" — {name}" if name and name != concept_id else ""
    code_paths = concept.get("code_paths") or []
    source = f" (`{code_paths[0]}`)" if code_paths else ""
    return f"- **`{concept_id}`**{label}{source}"


def _render_pillar_page(pillar: str, concepts: list[dict[str, Any]]) -> str:
    lines = [
        f"# {pillar}",
        "",
        "<!-- GENERATED by pipelines/scripts/build_skill_graph.py -- do not hand-edit. -->",
        "",
        f"{len(concepts)} concepts, sourced from `docs/concepts.yaml` "
        "(itself generated by `scripts/build_concepts_yaml.py` from "
        "`CONCEPT:<ID>` markers in `agent_utilities/`).",
        "",
    ]
    lines.extend(_render_concept_line(c) for c in sorted(concepts, key=lambda c: c.get("id", "")))
    return "\n".join(lines).rstrip() + "\n"


def _render_index_line(pillar: str, by_pillar: dict[str, list[dict[str, Any]]]) -> str:
    count = len(by_pillar.get(pillar, []))
    unit = "concept" if count == 1 else "concepts"
    return f"- [`{pillar}`]({slugify(pillar)}.md) ({count} {unit})"


def _render_index(pillars: list[str], by_pillar: dict[str, list[dict[str, Any]]]) -> str:
    lines = [
        "# Components",
        "",
        "agent-utilities' major components: the 9 concept pillars in",
        "`docs/concepts.yaml`, each generated from that registry, one page",
        "per pillar, listing every concept it owns.",
        "",
    ]
    lines.extend(_render_index_line(pillar, by_pillar) for pillar in pillars)
    return "\n".join(lines).rstrip() + "\n"


def render_components_au(repo_root: Path) -> dict[str, str]:
    """``{relative_path: content}`` for every pillar page plus the index."""
    data = _load_concepts(repo_root)
    if not data:
        return {}
    pillars = data.get("pillars") or []
    by_pillar = _group_by_pillar(data.get("concepts") or [])
    files = {
        f"components/{slugify(pillar)}.md": _render_pillar_page(pillar, by_pillar.get(pillar, []))
        for pillar in pillars
    }
    files["components/index.md"] = _render_index(pillars, by_pillar)
    return files
