"""One generated page per major (top-level) component for epistemic-graph
(RF-ADR-009 D4): the 6 top-level "layer boundary root seam" components in
``architecture/component-registry.yml``, each owning a set of child
implementation components -- see ``skill_graph/eg.py``.

``agent-utilities`` has a components tier too, generated from its own
``docs/concepts.yaml`` pillars instead -- see ``render_components_au.py``
(its own ``architecture/component-registry.yml`` has exactly 1 component,
too sparse to seed a tier). ``agent-connector-sdk``, ``graph-os``, and
``agent-webui`` have no comparable registry; their own docs nav already IS
their honest component tier (nav relabeled, not generated -- see
WRAPUP.md).
"""

from __future__ import annotations

from typing import Any

_REGISTRY_PREFIX = "component/epistemic-graph/registry/"


def _top_level_registry_components(corpus: dict[str, Any]) -> list[dict[str, Any]]:
    nodes_by_id = {n["id"]: n for n in corpus["@graph"]}
    child_ids = {
        child
        for node in corpus["@graph"]
        if node["id"].startswith(_REGISTRY_PREFIX)
        for child in (node.get("childComponent") or [])
    }
    return [
        nodes_by_id[node_id]
        for node_id in sorted(nodes_by_id)
        if node_id.startswith(_REGISTRY_PREFIX) and node_id not in child_ids
    ]


def _render_child_line(nodes_by_id: dict[str, Any], child_id: str) -> str:
    child = nodes_by_id.get(child_id)
    if not child:
        return f"- `{child_id}`"
    bits = [f"layer: {child['layer']}"] if child.get("layer") else []
    if child.get("status"):
        bits.append(f"status: {child['status']}")
    extra = f" ({', '.join(bits)})" if bits else ""
    summary = f" — {child['summary']}" if child.get("summary") else ""
    return f"- **`{child['label']}`**{extra}{summary}"


def _render_component_page(nodes_by_id: dict[str, Any], component: dict[str, Any]) -> str:
    lines = [
        f"# {component['label']}",
        "",
        "<!-- GENERATED by pipelines/scripts/build_skill_graph.py -- do not hand-edit. -->",
        "",
        f"Layer: `{component.get('layer', 'n/a')}` &nbsp;·&nbsp; "
        f"Status: `{component.get('status', 'n/a')}`",
        "",
    ]
    if component.get("summary"):
        lines.extend([component["summary"], ""])
    capability_ids = component.get("capabilityIds") or []
    if capability_ids:
        lines.append("**Capabilities:** " + ", ".join(f"`{c}`" for c in capability_ids))
        lines.append("")
    children = component.get("childComponent") or []
    if children:
        lines.append("## Child components")
        lines.append("")
        lines.extend(_render_child_line(nodes_by_id, child_id) for child_id in children)
        lines.append("")
    lines.append(
        "Source: `architecture/component-registry.yml` "
        f"(`component_id: {component['label']}`)."
    )
    return "\n".join(lines).rstrip() + "\n"


def render_index(components: list[dict[str, Any]]) -> str:
    lines = [
        "# Components",
        "",
        "The epistemic-graph engine's major components (the top-level layer",
        "boundary seams in `architecture/component-registry.yml`), each",
        "generated from that registry, one page per component.",
        "",
    ]
    lines.extend(f"- [`{c['label']}`]({_slug_path(c['label'])}.md)" for c in components)
    return "\n".join(lines).rstrip() + "\n"


def _slug_path(component_id: str) -> str:
    return component_id.replace(".", "-")


def render_components_eg(corpus: dict[str, Any]) -> dict[str, str]:
    """``{relative_path: content}`` for every major-component page plus the index."""
    nodes_by_id = {n["id"]: n for n in corpus["@graph"]}
    components = _top_level_registry_components(corpus)
    if not components:
        return {}
    files = {
        f"components/{_slug_path(c['label'])}.md": _render_component_page(nodes_by_id, c)
        for c in components
    }
    files["components/index.md"] = render_index(components)
    return files
