"""The man-page-tier reference page projected for one repo (RF-ADR-009 D2/D4)."""

from __future__ import annotations

from typing import Any

from skill_graph.model import repo_label
from skill_graph.render_shared import render_concept_components


def _header(name: str) -> list[str]:
    return [
        f"# {name} — generated skill-graph reference",
        "",
        "<!-- GENERATED by pipelines/scripts/build_skill_graph.py -- do not hand-edit. -->",
        "<!-- Regenerate: python3 build_skill_graph.py build --workspace <agent-packages> -->",
        "",
        '<div class="man-page" markdown>',
        "",
        "Every concept and component this repo's own registries and documentation "
        "nav declare, generated from the same cross-repo "
        "[skill graph](https://knuckles-team.github.io/pipelines/) corpus "
        "(RF-ADR-009 D1) that indexes all seven repos. This page is this repo's "
        "own slice of that corpus, not a duplicate authority -- the full machine "
        "corpus, with typed links, is published from `pipelines`.",
        "",
    ]


def render_repo_reference_md(corpus: dict[str, Any], slug: str) -> str:
    """Filter the corpus to one repo and render its man-page-tier reference page.

    Meant to be committed *inside that repo's own docs tree* (e.g.
    ``docs/reference/skill-graph.generated.md``), wrapped in the shared
    theme's ``.man-page`` CSS class -- the deepest, most detailed tier of that
    repo's information architecture, sitting below its hand-written intro and
    guide pages.
    """
    nodes_by_id = {n["id"]: n for n in corpus["@graph"]}
    concepts = [
        n
        for n in corpus["@graph"]
        if n["type"] == "Concept" and n.get("partOfRepo") == f"repo/{slug}"
    ]
    lines = _header(repo_label(slug))
    for concept in sorted(concepts, key=lambda n: n["label"]):
        lines.append(f"## {concept['label']}")
        lines.append("")
        render_concept_components(lines, nodes_by_id, concept, with_extra=True)
    lines.append("</div>")
    return "\n".join(lines).rstrip() + "\n"
