"""tracked-privacy fires on planted host data and catalog identities; the catalog is required."""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from tests.hooks.conftest import Repo

IDENTITY = "zorblaxian"


@pytest.fixture
def catalog(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> Path:
    monkeypatch.setenv("AGENT_UTILITIES_PRIVACY_IDENTIFIERS", "fixture-identity-token")
    path = tmp_path / "prohibited-identities.json"
    path.write_text(json.dumps({"version": "1", "identities": [IDENTITY]}), encoding="utf-8")
    return path


def test_privacy_passes_a_clean_repository(repo: Repo, catalog: Path) -> None:
    assert repo.run("tracked-privacy", "--identity-catalog", str(catalog)) == 0


def test_privacy_fires_on_a_real_home_path_in_runtime_source(repo: Repo, catalog: Path) -> None:
    repo.commit({"pkg/paths.py": "CACHE = '" + "/ho" + "me/realperson7/cache'\n"})
    assert repo.run("tracked-privacy", "--identity-catalog", str(catalog)) == 1


def test_privacy_accepts_a_documented_stand_in_account(repo: Repo, catalog: Path) -> None:
    repo.commit({"pkg/paths.py": "CACHE = '" + "/ho" + "me/example-user/cache'\n"})
    assert repo.run("tracked-privacy", "--identity-catalog", str(catalog)) == 0


def test_privacy_fires_on_a_catalog_identity_in_a_file_body(repo: Repo, catalog: Path) -> None:
    repo.commit({"docs/notes.md": f"Generated by {IDENTITY.capitalize()} tooling.\n"})
    assert repo.run("tracked-privacy", "--identity-catalog", str(catalog)) == 1


def test_privacy_cannot_run_without_its_catalog(repo: Repo, tmp_path: Path) -> None:
    assert repo.run("tracked-privacy", "--identity-catalog", str(tmp_path / "absent.json")) == 2
