"""ste gates: EG-STE-Lite language and staleness rules over docs and CLI strings.

Each test plants the exact finding a rule names, proves the gate reports it
(exit 1) or stays silent and advisory-only (exit 0), and proves the clean
repair passes. Gates run the real scanner and wordlist; nothing is mocked.
"""

from __future__ import annotations

import pytest

from pipelines_hooks.ste.sentences import sentence_spans
from tests.hooks.conftest import Repo

CLEAN = "# fixture\n\nThe gate runs the hook.\n"
BASE_README = "# fixture\n\nThe gate utilizes the wheel context.\n"
STE_STALE = (
    "[[tool.pipelines_hooks.ste.staleness]]\n"
    'pattern = "agent-utilities"\n'
    'message = "name the current package"\n'
)


def _pyproject(*ste: str) -> str:
    return (
        '[project]\nname = "fixture"\nversion = "0"\n\n'
        '[tool.pipelines_hooks]\npackages = ["pkg"]\n\n' + "".join(ste)
    )


def test_census_accepts_a_clean_doc(repo: Repo, capsys: pytest.CaptureFixture[str]) -> None:
    repo.commit({"README.md": CLEAN}, "docs")
    assert repo.run("ste-census") == 0
    assert "OK: no findings" in capsys.readouterr().out


def test_census_fires_on_an_overlong_sentence(repo: Repo, capsys: pytest.CaptureFixture[str]) -> None:
    readme = (
        "# fixture\n\n"
        "The gate runs the scan, the report, the export, the archive, the backup, "
        "the restore, the audit, and the replay for every commit.\n"
    )
    repo.commit({"README.md": readme})
    assert repo.run("ste-census") == 1
    assert "word sentence; the cap is 20" in capsys.readouterr().out


def test_census_fires_on_a_banned_word(repo: Repo, capsys: pytest.CaptureFixture[str]) -> None:
    repo.commit({"README.md": "# fixture\n\nThe tool utilizes the wheel context.\n"})
    assert repo.run("ste-census") == 1
    assert "utilizes -> use" in capsys.readouterr().out


@pytest.mark.parametrize("hedge", ["would", "might", "could"])
def test_census_fires_on_modal_hedges(repo: Repo, capsys: pytest.CaptureFixture[str], hedge: str) -> None:
    repo.commit({"README.md": f"# fixture\n\nThe build {hedge} fail closed.\n"})
    assert repo.run("ste-census") == 1
    assert f"modal hedge '{hedge}'" in capsys.readouterr().out


def test_required_modals_pass(repo: Repo) -> None:
    readme = (
        "# fixture\n\n"
        "The build must fail closed. The gate should log the error. "
        "The hook may skip locally.\n"
    )
    repo.commit({"README.md": readme})
    assert repo.run("ste-census") == 0


def test_capability_modal_is_advisory(repo: Repo, capsys: pytest.CaptureFixture[str]) -> None:
    repo.commit({"README.md": "# fixture\n\nThe tool can export a map.\n"})
    assert repo.run("ste-census") == 0
    out = capsys.readouterr().out
    assert "ADV" in out
    assert "modal 'can'" in out


def test_census_fires_on_fuzzy_quantities(repo: Repo, capsys: pytest.CaptureFixture[str]) -> None:
    repo.commit({"README.md": "# fixture\n\nThe gate keeps several retries.\n"})
    assert repo.run("ste-census") == 1
    out = capsys.readouterr().out
    assert "fuzzy quantity 'several'; state a measured value or mark it measured: ~N" in out


def test_advisory_fuzzy_quantity_passes(repo: Repo, capsys: pytest.CaptureFixture[str]) -> None:
    repo.commit({"README.md": "# fixture\n\nThe gate keeps some retries.\n"})
    assert repo.run("ste-census") == 0
    assert "fuzzy quantity 'some'" in capsys.readouterr().out


def test_census_fires_on_first_second_person(repo: Repo, capsys: pytest.CaptureFixture[str]) -> None:
    repo.commit({"README.md": "# fixture\n\nWe build the pack. You run the gate.\n"})
    assert repo.run("ste-census") == 1
    out = capsys.readouterr().out
    assert "person 'we'" in out
    assert "person 'you'" in out


def test_census_fires_on_an_idiom(repo: Repo, capsys: pytest.CaptureFixture[str]) -> None:
    repo.commit({"README.md": "# fixture\n\nThe tool offers a quick win.\n"})
    assert repo.run("ste-census") == 1
    assert "idiom 'quick win'" in capsys.readouterr().out


@pytest.mark.parametrize(
    ("prose", "fires"),
    [
        ("The gate fetches the lock. The tool retrieves the source.", True),
        ("The gate fetches the lock. The tool fetches the source.", False),
    ],
)
def test_cluster_fires_only_when_both_terms_appear(
    repo: Repo, capsys: pytest.CaptureFixture[str], prose: str, fires: bool
) -> None:
    repo.commit({"README.md": f"# fixture\n\n{prose}\n"})
    assert repo.run("ste-census") == (1 if fires else 0)
    out = capsys.readouterr().out
    if fires:
        assert "cluster terms fetch and retrieve both present; pick one term" in out
    else:
        assert "OK: no findings" in out


def test_passive_voice_is_advisory(repo: Repo, capsys: pytest.CaptureFixture[str]) -> None:
    repo.commit({"README.md": "# fixture\n\nThe report was generated by the tool.\n"})
    assert repo.run("ste-census") == 0
    assert "passive voice 'generated'" in capsys.readouterr().out


def test_allowlisted_participles_are_quiet(repo: Repo, capsys: pytest.CaptureFixture[str]) -> None:
    repo.commit({"README.md": "# fixture\n\nThe pack is used by the gate.\n"})
    assert repo.run("ste-census") == 0
    assert "OK: no findings" in capsys.readouterr().out


def test_noun_chain_is_advisory(repo: Repo, capsys: pytest.CaptureFixture[str]) -> None:
    repo.commit({"README.md": "# fixture\n\nThe packaging release engineering automation pipeline ships.\n"})
    assert repo.run("ste-census") == 0
    assert "five-or-more stacked content words" in capsys.readouterr().out


def test_masked_prose_is_not_scanned(repo: Repo, capsys: pytest.CaptureFixture[str]) -> None:
    masked = (
        "# fixture\n\n"
        "The gate `utilizes` the wheel.\n\n"
        "```\nutilize the wheel\n```\n\n"
        "The UTILIZE flag is set.\n\n"
        "See CONCEPT:FM.OS.governance.service-reads-fan-level for context.\n\n"
        "The Method::run form stays.\n\n"
        "<!-- generated:begin -->\nutilize the wheel\n<!-- generated:end -->\n"
    )
    repo.commit({"README.md": masked})
    assert repo.run("ste-census") == 0
    assert "OK: no findings" in capsys.readouterr().out


def test_link_targets_are_masked_and_link_text_is_prose(
    repo: Repo, capsys: pytest.CaptureFixture[str]
) -> None:
    repo.commit({"README.md": "# fixture\n\nThe gate ships [the release](docs/utilize.md) now.\n"})
    assert repo.run("ste-census") == 0
    assert "OK: no findings" in capsys.readouterr().out
    repo.commit({"README.md": "# fixture\n\nThe gate [leverages the wheel](docs/g.md) at build time.\n"})
    assert repo.run("ste-census") == 1
    assert "leverages -> use" in capsys.readouterr().out


def test_heading_content_is_scanned(repo: Repo, capsys: pytest.CaptureFixture[str]) -> None:
    repo.commit({"README.md": "# fixture\n\n## Utilization notes\n\nThe gate runs the hook.\n"})
    assert repo.run("ste-census") == 1
    assert "utilization -> use" in capsys.readouterr().out


def test_structural_lines_never_merge_into_sentence_runs(repo: Repo, capsys: pytest.CaptureFixture[str]) -> None:
    structural = (
        "# fixture\n\n"
        "![PyPI](https://img.shields.io/pypi/v/fixture)\n"
        "![CI](https://img.shields.io/github/workflow/fixture/ci.svg)\n\n"
        "| Rule | Cap |\n"
        "| ---- | --- |\n"
        "| S | 20 words |\n"
        "| C | one per pair |\n\n"
        "The gate runs the hook.\n"
    )
    repo.commit({"README.md": structural})
    assert repo.run("ste-census") == 0
    assert "OK: no findings" in capsys.readouterr().out


def test_census_fails_closed_without_an_in_scope_doc(repo: Repo, capsys: pytest.CaptureFixture[str]) -> None:
    assert repo.run("ste-census") == 2
    assert "CANNOT RUN" in capsys.readouterr().err


def test_an_unknown_ste_key_is_a_configuration_error(repo: Repo, capsys: pytest.CaptureFixture[str]) -> None:
    repo.commit({"pyproject.toml": _pyproject('[tool.pipelines_hooks.ste]\nbad = "x"\n'), "README.md": CLEAN})
    assert repo.run("ste-census") == 2
    assert "unknown key" in capsys.readouterr().err


def test_a_broken_staleness_pattern_is_a_configuration_error(repo: Repo, capsys: pytest.CaptureFixture[str]) -> None:
    broken = '[[tool.pipelines_hooks.ste.staleness]]\npattern = "("\nmessage = "stale"\n'
    repo.commit({"pyproject.toml": _pyproject(broken), "README.md": CLEAN})
    assert repo.run("ste-staleness-census") == 2
    assert "does not compile" in capsys.readouterr().err


@pytest.mark.parametrize("exempt", [True, False], ids=["exempt", "in-scope"])
def test_exemption_controls_path_scope(repo: Repo, exempt: bool) -> None:
    config = (
        '[tool.pipelines_hooks.ste]\nexempt = ["CHANGELOG.md"]\n'
        if exempt
        else ""
    )
    repo.commit(
        {
            "pyproject.toml": _pyproject(config),
            "README.md": CLEAN,
            "CHANGELOG.md": "# Changelog\n\nThe tool utilizes the wheel.\n",
        }
    )
    assert repo.run("ste-census") == (0 if exempt else 1)


def test_staged_passes_with_nothing_staged(repo: Repo, capsys: pytest.CaptureFixture[str]) -> None:
    assert repo.run("ste-staged") == 0
    assert "no in-scope file staged" in capsys.readouterr().out


def test_staged_does_not_recount_preexisting_findings(repo: Repo, capsys: pytest.CaptureFixture[str]) -> None:
    repo.commit({"README.md": BASE_README})
    repo.stage({"README.md": "# fixture\n\nThe pack ships the hook.\nThe gate utilizes the wheel context.\n"})
    assert repo.run("ste-staged") == 0
    assert "OK: no findings" in capsys.readouterr().out


def test_staged_fires_on_a_newly_added_finding(repo: Repo, capsys: pytest.CaptureFixture[str]) -> None:
    repo.commit({"README.md": BASE_README})
    repo.stage(
        {"README.md": "# fixture\n\nThe gate utilizes the wheel context.\nThe tool leverages the index.\n"}
    )
    assert repo.run("ste-staged") == 1
    out = capsys.readouterr().out
    assert "leverages -> use" in out
    assert "utilizes -> use" not in out


def test_staged_checks_a_new_doc_in_full(repo: Repo, capsys: pytest.CaptureFixture[str]) -> None:
    repo.commit({"README.md": CLEAN})
    repo.stage({"AGENTS.md": "# Agents\n\nThe gate utilizes the wheel.\n"})
    assert repo.run("ste-staged") == 1
    assert "utilizes -> use" in capsys.readouterr().out


def test_cli_strings_are_scanned(repo: Repo, capsys: pytest.CaptureFixture[str]) -> None:
    repo.commit(
        {
            "pyproject.toml": _pyproject('[tool.pipelines_hooks.ste]\ncode_paths = ["pkg"]\n'),
            "README.md": CLEAN,
            "pkg/cli.py": 'import argparse\n\nparser = argparse.ArgumentParser()\nparser.add_argument("--flag", help="utilize the wheel")\n',
        }
    )
    assert repo.run("ste-census") == 1
    out = capsys.readouterr().out
    assert "pkg/cli.py:" in out
    assert "utilize -> use" in out


def test_clean_cli_strings_pass(repo: Repo) -> None:
    repo.commit(
        {
            "pyproject.toml": _pyproject('[tool.pipelines_hooks.ste]\ncode_paths = ["pkg"]\n'),
            "README.md": CLEAN,
            "pkg/cli.py": 'import argparse\n\nparser = argparse.ArgumentParser()\nparser.add_argument("--flag", help="Use the wheel.")\n',
        }
    )
    assert repo.run("ste-census") == 0


def test_staleness_staged_fires_on_an_added_claim(repo: Repo, capsys: pytest.CaptureFixture[str]) -> None:
    repo.commit({"pyproject.toml": _pyproject(STE_STALE), "README.md": CLEAN})
    repo.stage({"README.md": "# fixture\n\nThe gate runs the hook.\nPowered by agent-utilities.\n"})
    assert repo.run("ste-staleness-staged") == 1
    assert "name the current package" in capsys.readouterr().out


def test_staleness_census_reports_and_clears(repo: Repo, capsys: pytest.CaptureFixture[str]) -> None:
    repo.commit(
        {"pyproject.toml": _pyproject(STE_STALE), "README.md": "# fixture\n\nPowered by agent-utilities.\n"}
    )
    assert repo.run("ste-staleness-census") == 1
    assert "name the current package" in capsys.readouterr().out
    repo.commit({"README.md": "# fixture\n\nThe pack owns the gate.\n"}, "docs")
    assert repo.run("ste-staleness-census") == 0


def test_staleness_gates_pass_without_patterns(repo: Repo, capsys: pytest.CaptureFixture[str]) -> None:
    repo.commit({"pyproject.toml": _pyproject(), "README.md": CLEAN})
    assert repo.run("ste-staleness-staged") == 0
    assert "no staleness patterns configured" in capsys.readouterr().out
    assert repo.run("ste-staleness-census") == 0
    assert "no staleness patterns configured" in capsys.readouterr().out


def test_abbreviations_do_not_end_sentences() -> None:
    protect = frozenset({"e.g."})
    assert len(sentence_spans("Use e.g. this. End.", protect)) == 2
    assert len(sentence_spans("Use e.g. this. End.", frozenset())) == 3


def test_abbreviation_protect_needs_a_word_boundary() -> None:
    protect = frozenset({"Ms."})
    assert len(sentence_spans("The gate audits stale claims. The run ends.", protect)) == 2
