"""tracked-privacy fires on planted host data and catalog identities; the catalog is required."""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from tests.hooks.conftest import Repo

IDENTITY = "zorblaxian"


@pytest.fixture
def catalog(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> Path:
    monkeypatch.setenv("AGENT_UTILITIES_PRIVACY_IDENTIFIERS", "fixture-identity-token")
    path = tmp_path / "prohibited-identities.json"
    path.write_text(json.dumps({"version": "1", "identities": [IDENTITY]}), encoding="utf-8")
    return path


def test_privacy_passes_a_clean_repository(repo: Repo, catalog: Path) -> None:
    assert repo.run("tracked-privacy", "--identity-catalog", str(catalog)) == 0


def test_privacy_fires_on_a_real_home_path_in_runtime_source(repo: Repo, catalog: Path) -> None:
    repo.commit({"pkg/paths.py": "CACHE = '" + "/ho" + "me/realperson7/cache'\n"})
    assert repo.run("tracked-privacy", "--identity-catalog", str(catalog)) == 1


def test_privacy_accepts_a_documented_stand_in_account(repo: Repo, catalog: Path) -> None:
    repo.commit({"pkg/paths.py": "CACHE = '" + "/ho" + "me/example-user/cache'\n"})
    assert repo.run("tracked-privacy", "--identity-catalog", str(catalog)) == 0


def test_privacy_fires_on_a_catalog_identity_in_a_file_body(repo: Repo, catalog: Path) -> None:
    repo.commit({"docs/notes.md": f"Generated by {IDENTITY.capitalize()} tooling.\n"})
    assert repo.run("tracked-privacy", "--identity-catalog", str(catalog)) == 1


def test_privacy_cannot_run_without_its_catalog(repo: Repo, tmp_path: Path) -> None:
    assert repo.run("tracked-privacy", "--identity-catalog", str(tmp_path / "absent.json")) == 2


def test_privacy_skips_locally_without_its_catalog(repo: Repo, tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.delenv("CI")
    assert repo.run("tracked-privacy", "--identity-catalog", str(tmp_path / "absent.json")) == 0


def test_a_malformed_catalog_is_not_downgraded_locally(repo: Repo, tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.delenv("CI")
    malformed = tmp_path / "catalog.json"
    malformed.write_text("{not json", encoding="utf-8")
    assert repo.run("tracked-privacy", "--identity-catalog", str(malformed)) == 2


def test_privacy_allows_a_hyphenated_requirement_id_citation(repo: Repo, catalog: Path) -> None:
    """A requirement ID like ``GRAPHOS-FLEET-R016`` is not a fleet host alias.

    Regression for the false-positive flood that broke requirement-ID
    citations in graph-os PRs: ``MACHINE_HOST_ID_RE``'s lookbehind excluded
    only alnum characters, so the hyphen immediately before ``R016`` never
    blocked the match and the requirement ID itself read as a host.
    """
    repo.commit({"docs/notes.md": "See GRAPHOS-FLEET-R016 and GRAPHOS-FLEET-R017 for scope.\n"})
    assert repo.run("tracked-privacy", "--identity-catalog", str(catalog)) == 0


def test_privacy_still_fires_on_a_bare_host_token(repo: Repo, catalog: Path) -> None:
    """A bare fleet host alias (no hyphen boundary) must still be caught."""
    repo.commit({"docs/notes.md": "Deployed to " + "rw" + "710 for the pilot.\n"})
    assert repo.run("tracked-privacy", "--identity-catalog", str(catalog)) == 1
