"""Five-core-repo documentation parity receipt (RF-ADR-009 D5).

Checks epistemic-graph, agent-utilities, agent-connector-sdk, graph-os, and
agent-webui against the shared documentation standard this Phase D pass
established, and renders a receipt (``pages/parity.md``): does each repo
inherit the shared MkDocs theme byte-for-byte (``sync_mkdocs_theme.py
check``), carry zero Mermaid fences / ASCII box-drawing in its docs, and
have the generated skill_graph man-page reference (D1/D2/D4) present and
linked into nav.

This is a snapshot, not a gate: no repo in scope has landed its docs/phase-d
branch yet, so most rows below describe that branch's content, read directly
from each repo's own worktree -- not (yet) from its ``main``. Re-run after
landing to get a true fleet-wide receipt.

Usage::

    python check_five_repo_parity.py --workspace <agent-packages> [--worktree-suffix docs-phase-d]
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path

from sync_mkdocs_theme import sync_theme

CORE_REPOS = (
    "epistemic-graph",
    "agent-utilities",
    "agent-connector-sdk",
    "graph-os",
    "agent-webui",
)

_BOX_DRAWING = re.compile("[─-╿]")


def _read_text(path: Path) -> str:
    try:
        return path.read_text(encoding="utf-8", errors="ignore")
    except OSError:
        return ""


def _docs_scan(repo_root: Path) -> tuple[int, int]:
    """(files with a mermaid fence, files with ASCII box-drawing) under docs/."""
    docs_dir = repo_root / "docs"
    if not docs_dir.is_dir():
        return (0, 0)
    mermaid = 0
    ascii_art = 0
    for path in docs_dir.rglob("*.md"):
        text = _read_text(path)
        if "```mermaid" in text:
            mermaid += 1
        if _BOX_DRAWING.search(text):
            ascii_art += 1
    return (mermaid, ascii_art)


_PIPELINES_ROOT = Path(__file__).resolve().parents[1]


def check_repo(repo_root: Path, slug: str) -> dict[str, object]:
    mkdocs_text = _read_text(repo_root / "mkdocs.yml")
    inherits = mkdocs_text.startswith("INHERIT:")
    theme_mismatches: list[str] = []
    if inherits:
        theme_mismatches = sync_theme(
            source_root=_PIPELINES_ROOT, repository_root=repo_root, content_source="docs", mode="check"
        )
    mermaid_files, ascii_files = _docs_scan(repo_root)
    man_page = repo_root / "docs" / "reference" / "skill-graph.generated.md"
    return {
        "repo": slug,
        "inherits_shared_theme": inherits,
        "shared_theme_byte_parity": inherits and not theme_mismatches,
        "theme_mismatches": theme_mismatches,
        "mermaid_fence_files": mermaid_files,
        "ascii_box_files": ascii_files,
        "skill_graph_reference_present": man_page.is_file(),
        "skill_graph_reference_in_nav": "skill-graph.generated.md" in mkdocs_text,
        "has_components_nav_tier": bool(re.search(r"^\s*-\s*Components:", mkdocs_text, re.MULTILINE)),
    }


def _row(result: dict[str, object]) -> str:
    def flag(value: object) -> str:
        return "yes" if value else "**no**"

    return (
        f"| {result['repo']} | {flag(result['inherits_shared_theme'])} "
        f"| {flag(result['shared_theme_byte_parity'])} "
        f"| {result['mermaid_fence_files']} | {result['ascii_box_files']} "
        f"| {flag(result['skill_graph_reference_present'] and result['skill_graph_reference_in_nav'])} "
        f"| {flag(result['has_components_nav_tier'])} |"
    )


def render_receipt(results: list[dict[str, object]]) -> str:
    lines = [
        "# Five-repo parity receipt",
        "",
        "Snapshot against the shared documentation standard (RF-ADR-009 D3-D5) "
        "for the five core repos, generated by "
        "`scripts/check_five_repo_parity.py`. A repo's own `docs/phase-d` "
        "branch is read directly when it exists; otherwise its live `main`.",
        "",
        "| Repo | Inherits shared theme | Theme byte-parity | Mermaid files | "
        "ASCII-art files | Skill graph reference | Components nav tier |",
        "|---|---|---|---|---|---|---|",
    ]
    lines.extend(_row(result) for result in results)
    lines.append("")
    theme_gaps = [r["repo"] for r in results if not r["inherits_shared_theme"]]
    if theme_gaps:
        lines.append(
            f"**Theme wiring gap:** {', '.join(theme_gaps)} do not yet declare `INHERIT:`.\n"
        )
    content_gaps = [
        r["repo"] for r in results if r["mermaid_fence_files"] or r["ascii_box_files"]
    ]
    if content_gaps:
        lines.append(
            f"**Known content gap, not this pass's to close:** {', '.join(content_gaps)} "
            "already inherit the shared theme (D3's wiring is done) but still carry "
            "Mermaid fences / ASCII box-drawing in hand-written prose -- a large,"
            " repo-owned content migration. Their generated docs "
            "(docs/capabilities.generated.md, docs/status.md, docs/concepts.yaml, etc.) "
            "are also under active concurrent feature lanes; the finish-line docs lane's "
            "collision rule defers touching either until those lanes land (see "
            "WRAPUP.md's D6 rehome plan)."
        )
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--workspace", type=Path, required=True)
    parser.add_argument(
        "--worktree-root",
        type=Path,
        default=Path("/var/tmp/repository-worktrees"),
        help="prefer <root>/<repo>/<suffix> over --workspace/<repo> when it exists",
    )
    parser.add_argument("--worktree-suffix", default="docs-phase-d")
    parser.add_argument("--out", type=Path, default=Path(__file__).resolve().parents[1] / "pages" / "parity.md")
    args = parser.parse_args(argv)
    results = []
    for slug in CORE_REPOS:
        candidate = args.worktree_root / slug / args.worktree_suffix
        repo_root = candidate if candidate.is_dir() else args.workspace / slug
        results.append(check_repo(repo_root, slug))
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(render_receipt(results), encoding="utf-8")
    print(f"parity receipt: wrote {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
