name: Tag Latest Release

on:
  push:
    branches:
      - 'main'

jobs:
  tag:
    runs-on: self-hosted
    permissions: write-all    
    steps:    
    - name: Checkout Repository
      uses: actions/checkout@v2.3.4

    - name: Get Latest Tag
      id: latest_tag
      run: |
        git fetch         
        git reset --hard origin/main
        git pull
        TAG=$(git tag | tail -n1)
        CURRENT_COMMIT=$(git rev-list -n 1 $TAG)
        LATEST_COMMIT=$(git rev-parse --verify HEAD)
        COMMIT_DIFFERENCE=$(git log ${CURRENT_COMMIT}..${LATEST_COMMIT} --pretty=oneline | wc -l)
        COMMIT_MESSAGE=$(git log --format=%B -n $COMMIT_DIFFERENCE $LATEST_COMMIT)
        echo -e "TAG=$TAG\nLATEST_COMMIT=$LATEST_COMMIT\nCURRENT_COMMIT=$CURRENT_COMMIT\nCOMMIT_DIFFERENCE=$COMMIT_DIFFERENCE\nCOMMIT_MESSAGE="$COMMIT_MESSAGE"" | tee -a $GITHUB_ENV
      
    - name: Delete Latest Tag
      if: ${{ env.TAG != '' }}
      id: delete_tag
      run: git push --delete origin ${{ env.TAG }}
         
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: latest
        release_name: Release Commit - ${{ env.LATEST_COMMIT }}
        body: |
          Changes in this Release - ${{ github.LATEST_COMMIT }}
          ${{ env.COMMIT_MESSAGE }}
        draft: false
        prerelease: false
