name: Tag Latest Release

on:
  push:
    branches:
      - 'main'

jobs:
  tag:
    runs-on: self-hosted
    permissions: write-all    
    steps:    
    - name: Checkout Repository
      uses: actions/checkout@v2.3.4

    - name: Get Latest Tag
      id: latest_tag
      run: |
        TAG=$(git tag | tail -n1)
        echo -e "TAG=$TAG" >> $GITHUB_ENV
      
    - name: Delete Latest Tag
      if: ${{ env.TAG != '' }}
      id: delete_tag
      run: |
         git fetch
         git reset --hard origin/main
         git push --delete origin $TAG
         
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: latest
        release_name: "Release Commit: $GITHUB_SHA"
        body: |
          Changes in this Release - ${{ github.ref }}
        draft: false
        prerelease: false
