name: Release Python Package

on:
  workflow_call:
    secrets:
      PYPI_API_TOKEN:
        required: true

permissions:
  contents: read

jobs:
  publish-pypi:
    runs-on: self-hosted
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Build, publish and release
        uses: ./.github/actions/publish-python-package
        with:
          pypi-token: ${{ secrets.PYPI_API_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
