name: Deploy Service

on:
  workflow_call:
    secrets:
      RUNNERS:
        required: true

jobs:
  services:
    runs-on: self-hosted
    permissions: write-all    
    steps:    
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Download Environment Artifact
      uses: actions/download-artifact@master
      with:
        name: environment_file
        path: .

    - name: Set Environment Variables
      id: env_vars
      run: |
        cat ./.env | tee -a $GITHUB_ENV
        source ./.env

    - name: Cleanup Artifacts
      id: cleanup
      uses: geekyeggo/delete-artifact@v2
      with:
        name: environment_file

    - name: Pull Image
      id: pull_image
      run: docker compose pull

    - name: Build Image
      id: build_image
      run: docker compose build

    - name: Bring Down Services
      id: services_down
      run: docker compose down || echo "Services Appear to be Down Already"

    - name: Bring Up Services
      id: services_up
      run: |
        echo "Running ${{ secrets.RUNNERS }} instances"
        docker compose up --build --scale runner=${{ secrets.RUNNERS }} -d

