name: Deploy Service

on:
  workflow_call:
    secrets:
      RUNNERS:
        required: true

permissions:
  contents: read

jobs:
  services:
    runs-on: self-hosted
    permissions:
      actions: write
      contents: read
    steps:
    - name: Checkout Repository
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false

    - name: Download Environment Artifact
      uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
      with:
        name: environment_file
        path: .

    - name: Set Environment Variables
      id: env_vars
      run: |
        cat ./.env >> $GITHUB_ENV
        source ./.env

    - name: Cleanup Artifacts
      id: cleanup
      uses: geekyeggo/delete-artifact@176a747ab7e287e3ff4787bf8a148716375ca118 # v6.0.0
      with:
        name: environment_file

    - name: Pull Image
      id: pull_image
      run: docker compose pull

    - name: Build Image
      id: build_image
      run: docker compose build

    - name: Bring Down Services
      id: services_down
      run: docker compose down || echo "Services Appear to be Down Already"

    - name: Bring Up Services
      id: services_up
      run: |
        echo "Running ${{ secrets.RUNNERS }} instances"
        docker compose up --build --scale runner=${{ secrets.RUNNERS }} -d
