name: Deploy Service

on:
  workflow_call:
    secrets:
      RUNNERS:
        required: true

jobs:
  services:
    runs-on: self-hosted
    permissions: write-all    
    steps:    
    - name: Checkout Repository
      uses: actions/checkout@v2.3.4
    - name: Pull Image
      id: pull_image
      run: docker-compose pull
    - name: Build Image
      id: build_image
      run: docker-compose build
    - name: Bring Down Services
      id: services_down
      run: docker-compose down
    - name: Bring Up Services
      id: services_up
      run: docker-compose up -d --runners=${{ env.RUNNERS }}
