name: Deploy Service

on:
  workflow_call:
    secrets:
      RUNNERS:
        required: true

jobs:
  services:
    runs-on: self-hosted
    permissions: write-all    
    steps:    
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: Download Environment Artifact
      uses: actions/download-artifact@master
      with:
        name: environment_file
        path: .
    - name: Pull Image
      id: pull_image
      run: docker compose pull
    - name: Build Image
      id: build_image
      run: docker compose build
    - name: Bring Down Services
      id: services_down
      run: docker compose down || echo "Services Appear to be Down Already"
    - name: Bring Up Services
      id: services_up
      run: docker compose up --build --scale runner=${{ env.RUNNERS }} -d
    - name: Cleanup Artifacts
      id: cleanup
      env:
        GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
      run: |
        echo "::add-mask::$GITHUB_TOKEN"
        curl --verbose --fail --show-error --location --request POST "https://api.github.com/repos/$GITHUB_REPOSITORY/dispatches" --header "Authorization: token $GITHUB_TOKEN" --header 'Content-Type: application/json' --header 'Accept: application/vnd.github.everest-preview+json' --data-raw "{ \"event_type\": \"delete_all_artifacts\", \"client_payload\": {\"parent_runid\": \"$GITHUB_RUN_ID\", \"parent_repo\": \"$GITHUB_REPOSITORY\"} }"
        echo "Cleaned artifacts"