name: Deploy Service

on:
  workflow_call:
    secrets:
      RUNNERS:
        required: true

permissions:
  contents: read

jobs:
  services:
    runs-on: self-hosted
    permissions:
      contents: read
    steps:
    - name: Checkout Repository
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false
